name: deploy
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Unshallow
      run: git fetch --prune --unshallow

    - uses: actions/setup-go@v2.1.3
      with:
        go-version: "1.14.3"

    - run: sudo apt-get update
    - run: sudo apt-get -qq -y install gnupg2 libdevmapper-dev libgpgme-dev libc6-dev-i386 btrfs-progs
    - name: set previous release tag for goreleaser
      shell: bash
      run: |
        echo ::set-env name=GORELEASER_PREVIOUS_TAG::$(curl --silent "https://api.github.com/repos/replicatedhq/kots/releases/latest" | grep -Po '"tag_name": "\K.*?(?=")')

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v2.2.1
      with:
        version: latest
        args: release --rm-dist --config deploy/.goreleaser.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
